# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  shift_pro_app_nginx:
    restart: always
    build:
      context: ./client
    ports:
    - "3000:80"
    depends_on:
    - shift_pro_server

  shift_pro_mysql:
    container_name: shiftpro_mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: shiftproscheduler
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
    - "3306:3306"
    volumes:
    - ./server/src/main/resources/db/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  shift_pro_server:
    restart: always
    build:
      context: ./server
    volumes:
    - ./server:/server
    - ~/.m2:/root/.m2
    ports:
    - "8080:8080"
    depends_on:
    - shift_pro_mysql
